apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mbbak
  labels:
    app: mbbak
spec:
  concurrencyPolicy: Forbid
  schedule: 0 2 * * *
  jobTemplate:
    metadata:
      labels:
        app: mbbak
    spec:
      template: 
        spec: 
          containers:
          - name: mbbak
            image: origuchi4k/mbbak
            volumeMounts:
              - name: backup-vol
                mountPath: /backup
            env:
              - name: DB_HOST
                value: my-db
              - name: DB_PASSWORD
                value: password
          restartPolicy: OnFailure
          volumes:
            - name: backup-vol
              hostPath: 
                path: /backup
                type: Directory
      backoffLimit: 3
